In [1]:
students = [
    ["Aarav", 85, 78, 92],
    ["Riya", 91, 88, 95],
    ["Kabir", 72, 69, 80],
]

In [2]:
students

[['Aarav', 85, 78, 92], ['Riya', 91, 88, 95], ['Kabir', 72, 69, 80]]

In [3]:
type(students)

list

In [4]:
import pandas as pd

In [5]:
# code here
students = [
    ["Alice", 21, "Pune", 85],
    ["Bob", 22, "Mumbai", 91],
    ["Charlie", 20, "Pune", 78]
]
print(students)

df = pd.DataFrame(
    students,
    columns=["Name", "Age", "City", "Score"]
)
print('\n')
print(df)

[['Alice', 21, 'Pune', 85], ['Bob', 22, 'Mumbai', 91], ['Charlie', 20, 'Pune', 78]]


      Name  Age    City  Score
0    Alice   21    Pune     85
1      Bob   22  Mumbai     91
2  Charlie   20    Pune     78

In [6]:
# code here

## Try this with the df you have created and see what all output you get?

df.head(1)

    Name  Age  City  Score
0  Alice   21  Pune     85

In [7]:
df.tail(1)

      Name  Age  City  Score
2  Charlie   20  Pune     78

In [8]:

df.shape

(3, 4)

In [9]:

df.columns

Index(['Name', 'Age', 'City', 'Score'], dtype='str')

In [10]:

df.index

RangeIndex(start=0, stop=3, step=1)

In [11]:
df["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [12]:

df.dtypes

Name       str
Age      int64
City       str
Score    int64
dtype: object

In [13]:
df.info

<bound method DataFrame.info of       Name  Age    City  Score
0    Alice   21    Pune     85
1      Bob   22  Mumbai     91
2  Charlie   20    Pune     78>

In [14]:
df.describe

<bound method NDFrame.describe of       Name  Age    City  Score
0    Alice   21    Pune     85
1      Bob   22  Mumbai     91
2  Charlie   20    Pune     78>

In [15]:
df[["Name", "Score"]]

      Name  Score
0    Alice     85
1      Bob     91
2  Charlie     78

In [16]:
df[["City"]]

     City
0    Pune
1  Mumbai
2    Pune

In [17]:
df[["Name", "City"]]

      Name    City
0    Alice    Pune
1      Bob  Mumbai
2  Charlie    Pune

In [18]:
df[["Name", "Age", "Score"]]

      Name  Age  Score
0    Alice   21     85
1      Bob   22     91
2  Charlie   20     78

In [25]:
type(df["Age"])

pandas.Series

In [20]:
df["Name"].dtype

In [21]:
type(df)

pandas.DataFrame

In [22]:
df.iloc[0]

Name     Alice
Age         21
City      Pune
Score       85
Name: 0, dtype: object

In [26]:
df.iloc[1]

Name        Bob
Age          22
City     Mumbai
Score        91
Name: 1, dtype: object

In [23]:
df.iloc[0:2]

    Name  Age    City  Score
0  Alice   21    Pune     85
1    Bob   22  Mumbai     91

In [27]:
df.iloc[0:2, 0:2]

    Name  Age
0  Alice   21
1    Bob   22

In [29]:
df.loc[0]

Name     Alice
Age         21
City      Pune
Score       85
Name: 0, dtype: object

In [32]:
df.loc[1]

Name        Bob
Age          22
City     Mumbai
Score        91
Name: 1, dtype: object

In [35]:
df.iloc[-1]

Name     Charlie
Age           20
City        Pune
Score         78
Name: 2, dtype: object

In [45]:
df.loc[1, ["Name", "Age"]]

Name    Bob
Age      22
Name: 1, dtype: object

In [46]:
df.iloc[1, 3]

np.int64(91)

In [31]:
df_custom = df.copy()

df_custom.index = ["student_A", "student_B", "student_C"]

df_custom

              Name  Age    City  Score
student_A    Alice   21    Pune     85
student_B      Bob   22  Mumbai     91
student_C  Charlie   20    Pune     78

In [47]:
df.loc[0]

Name     Alice
Age         21
City      Pune
Score       85
Name: 0, dtype: object

In [48]:
df_custom = df.copy()

df_custom.index = ["student_A", "student_B", "student_C"]

df_custom

              Name  Age    City  Score
student_A    Alice   21    Pune     85
student_B      Bob   22  Mumbai     91
student_C  Charlie   20    Pune     78

In [49]:
df_custom.loc["student_B"]

Name        Bob
Age          22
City     Mumbai
Score        91
Name: student_B, dtype: object

In [50]:
df_custom.iloc[1]

Name        Bob
Age          22
City     Mumbai
Score        91
Name: student_B, dtype: object

In [51]:
df_custom.loc["student_B", "Score"]

np.int64(91)

In [52]:
df_custom.loc["student_B", ["Name", "City", "Score"]]

Name        Bob
City     Mumbai
Score        91
Name: student_B, dtype: object

In [53]:
df_custom.loc[["student_A", "student_C"]]

              Name  Age  City  Score
student_A    Alice   21  Pune     85
student_C  Charlie   20  Pune     78

In [60]:
df_custom.loc["student_A"]
#we did try travesing through labels

Name     Alice
Age         21
City      Pune
Score       85
Name: student_A, dtype: object

In [61]:
df_custom.loc["student_C", "City"]
#it is doing the  city update

'Pune'

In [62]:
df_custom.loc["student_B", ["Name", "Score"]]
#we have to get name and score of stu3

Name     Bob
Score     91
Name: student_B, dtype: object

In [57]:
df_custom.loc[["student_A", "student_C"]]

              Name  Age  City  Score
student_A    Alice   21  Pune     85
student_C  Charlie   20  Pune     78

In [65]:
df_custom.loc["student_A":"student_B"]

            Name  Age    City  Score
student_A  Alice   21    Pune     85
student_B    Bob   22  Mumbai     91

In [59]:
df_custom.loc[["student_A", "student_C"], ["Name", "Score"]]

              Name  Score
student_A    Alice     85
student_C  Charlie     78