### Why do we need filtering?

Suppose our DataFrame contains hundreds or thousands of rows.

We don't always want the entire DataFrame.

Instead, we may want to ask questions such as:

"Show me only the students whose Python marks are greater than 80."

We have already seen Boolean conditions in Python:

In [1]:
import pandas as pd

In [2]:
# code here
# Pandas way - much cleaner and more intuitive!
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Python': [85, 92, 78, 90],
    'Maths': [99, 85, 88, 50],
    'Chemistry' : [90, 65, 75, 80],
    'Physics' : [85, 65, 87, 33],
    'Department' : ['SCMS', 'SCMS', 'CS', 'Physics']
})


df

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
1      Bob      92     85         65       65       SCMS
2  Charlie      78     88         75       87         CS
3    Diana      90     50         80       33    Physics

Try these line below and try to retrive the values from the Physics column where the score is grater than 80

```python
df["Physics"] >80

df.iloc[:,4]

df.loc[:,'Physics'] 

Which rows do you expect to be True?

In [3]:
df["Physics"] >80

0     True
1    False
2     True
3    False
Name: Physics, dtype: bool

In [4]:
df.iloc[:,4]

0    85
1    65
2    87
3    33
Name: Physics, dtype: int64

In [5]:
df.loc[:,'Physics']

0    85
1    65
2    87
3    33
Name: Physics, dtype: int64

Now you can apply this boolean mask to the data Frame created to get the filterd data

```python 
mask = df["Physics"] >80
print(mask )
df[mask]

In [6]:
#code here
mask = df["Physics"] > 80

In [7]:
print(mask )

0     True
1    False
2     True
3    False
Name: Physics, dtype: bool

In [8]:
df[mask]

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
2  Charlie      78     88         75       87         CS

Try the following and notice the same logic above is being implemented directly in the df
```python
df[df["Python"] > 80]

In [9]:
# code here
df[df["Python"] > 80]

    Name  Python  Maths  Chemistry  Physics Department
0  Alice      85     99         90       85       SCMS
1    Bob      92     85         65       65       SCMS
3  Diana      90     50         80       33    Physics

<span style="color: cyan;">@ Think</span>

will the following line give an error ? 
```python 
df[df["Python"] > 100]

In [10]:
#code here
df[df["Python"] > 100]

Empty DataFrame
Columns: [Name, Python, Maths, Chemistry, Physics, Department]
Index: []

In [11]:
df[df["Python"] > 80]

    Name  Python  Maths  Chemistry  Physics Department
0  Alice      85     99         90       85       SCMS
1    Bob      92     85         65       65       SCMS
3  Diana      90     50         80       33    Physics

In [12]:
mask = df["Physics"] > 80
print(mask)
df[mask]

0     True
1    False
2     True
3    False
Name: Physics, dtype: bool

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
2  Charlie      78     88         75       87         CS

### Combining Conditions
Real questions are often more complicated.

For example:

Find students who scored more than 80 in both Maths and Python.

In normal Python, we might think about using:
> and

But Pandas works differently when comparing an entire Series.

For element-by-element logical operations, we use:

| Operation | Pandas operator |   |
| --------- | --------------- | - |
| AND       | `&`             |   |
| OR        | l           |   |
| NOT       | `~`             |   |


When combining conditions, **put each condition inside parentheses.**

```python 
df[(df['Physics']>80) & (df['Maths']>84)]
df[(df['Physics']>80) | (df['Maths']>84)]
df[~(df['Physics']>80)]

In [13]:
#code here
df[(df['Physics'] > 80) & (df['Maths'] > 84)]

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
2  Charlie      78     88         75       87         CS

In [14]:

df[(df['Physics'] > 80) | (df['Maths'] > 84)]

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
1      Bob      92     85         65       65       SCMS
2  Charlie      78     88         75       87         CS

In [15]:

df[~(df['Physics'] > 80)]

    Name  Python  Maths  Chemistry  Physics Department
1    Bob      92     85         65       65       SCMS
3  Diana      90     50         80       33    Physics

### Filtering with isin()

Sometimes we don't want to write a numerical condition.

Suppose we want students from specific departments: Physics

We could write multiple conditions, but Pandas provides a convenient method:

>isin()

```python
df['Sports'] = ['yes','no','yes','yes']
print(df)
df['Sports'].isin(['yes'])

or
df['Physics'].isin([65,85])

In [16]:
#code here
df[(df["Physics"] > 80) & (df["Maths"] > 84)]

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
2  Charlie      78     88         75       87         CS

In [17]:
df['Sports'] = ['yes', 'no', 'yes', 'yes']
print(df)

df['Sports'].isin(['yes'])

      Name  Python  Maths  Chemistry  Physics Department Sports
0    Alice      85     99         90       85       SCMS    yes
1      Bob      92     85         65       65       SCMS     no
2  Charlie      78     88         75       87         CS    yes
3    Diana      90     50         80       33    Physics    yes

0     True
1    False
2     True
3     True
Name: Sports, dtype: bool

In [18]:
df['Physics'].isin([65, 85])

0     True
1     True
2    False
3    False
Name: Physics, dtype: bool

In [19]:
df[df['Sports'].isin(['yes'])]

      Name  Python  Maths  Chemistry  Physics Department Sports
0    Alice      85     99         90       85       SCMS    yes
2  Charlie      78     88         75       87         CS    yes
3    Diana      90     50         80       33    Physics    yes

### Filtering a Range with between()

Another common question is:

"Give me students whose Python marks are between 80 and 95."

we could write 
>(df["Python"] >= 80) & (df["Python"] <= 95)

But Pandas also provides us

>between()

```python
df["Python"].between(80, 95)
df[df["Python"].between(80, 95)]

In [20]:
#code here
df["Python"].between(80, 95)

0     True
1     True
2    False
3     True
Name: Python, dtype: bool

In [21]:

df[df["Python"].between(80, 95)]

    Name  Python  Maths  Chemistry  Physics Department Sports
0  Alice      85     99         90       85       SCMS    yes
1    Bob      92     85         65       65       SCMS     no
3  Diana      90     50         80       33    Physics    yes

In [22]:
#cleaner version
(df["Python"] >= 80) & (df["Python"] <= 95)

0     True
1     True
2    False
3     True
Name: Python, dtype: bool

### Creating New Columns

So far, we've mostly asked questions about existing data.

Now let's create new information from our existing columns.

Suppose we want to calculate each student's average marks.

We already know how to perform arithmetic in Python and NumPy.

We can apply the same idea directly to Pandas columns.

```python 
df["Average"] = (
    df["Maths"] +
    df["Physics"] +
    df["Python"]
) / 3

df

In [23]:
#code here
df["Average"] = (
    df["Maths"] +
    df["Physics"] +
    df["Python"]
) / 3

df

      Name  Python  Maths  Chemistry  Physics Department Sports    Average
0    Alice      85     99         90       85       SCMS    yes  89.666667
1      Bob      92     85         65       65       SCMS     no  80.666667
2  Charlie      78     88         75       87         CS    yes  84.333333
3    Diana      90     50         80       33    Physics    yes  57.666667

<span style="color:cyan">Important idea</span>


df["Maths"] + df["Physics"]

doesn't require a loop.

Pandas performs the operation across the corresponding values.

This should look familiar from our NumPy work:

Vectorised operations

### Inspecting Unique Values

For example:

What departments are present in our dataset?

We can use:

> unique()

```python
df["Department"].unique()

sometime we only need number of unique values 

df["Department"].nunique()

In [24]:
#code here
df["Department"].unique()

array(['SCMS', 'CS', 'Physics'], dtype=object)

In [25]:
df["Department"].nunique()

3

### Counting Categories with value_counts()

Suppose we want to know:

How many students belong to each department?

We could write loops and manually count them.

Pandas provides:

>value_count()

```python 
df['Department'].value_counts()

In [26]:
#code here
df['Department'].value_counts()

Department
SCMS       2
CS         1
Physics    1
Name: count, dtype: int64

In [27]:
subject_averages = df[['Python', 'Maths', 'Chemistry', 'Physics']].mean()

subject_averages

Python       86.25
Maths        80.50
Chemistry    77.50
Physics      67.50
dtype: float64

In [28]:
df[
    (df["Python"] < subject_averages["Python"]) &
    (df["Maths"] < subject_averages["Maths"]) &
    (df["Chemistry"] < subject_averages["Chemistry"]) &
    (df["Physics"] < subject_averages["Physics"])
]

Empty DataFrame
Columns: [Name, Python, Maths, Chemistry, Physics, Department, Sports, Average]
Index: []

### <span style='color:green'>To do</span>
Solve the following 4 tasks with the modules learned above 
1. Find all the students with less than average marks for each subject
2. Get the list of students who have scored more than 80 and are in SCMS
3. Add a new column in which all the student scoring more than 70 marks pass and other fail (use between())
4. list all teh student passed

In [29]:
subject_avg = df[['Python', 'Maths', 'Chemistry', 'Physics']].mean()
subject_avg

Python       86.25
Maths        80.50
Chemistry    77.50
Physics      67.50
dtype: float64

In [30]:
df[
    (df['Python'] < subject_avg['Python']) &
    (df['Maths'] < subject_avg['Maths']) &
    (df['Chemistry'] < subject_avg['Chemistry']) &
    (df['Physics'] < subject_avg['Physics'])
]

Empty DataFrame
Columns: [Name, Python, Maths, Chemistry, Physics, Department, Sports, Average]
Index: []

In [31]:
df[(df['Python'] > 80) & (df['Department'] == 'SCMS')]

    Name  Python  Maths  Chemistry  Physics Department Sports    Average
0  Alice      85     99         90       85       SCMS    yes  89.666667
1    Bob      92     85         65       65       SCMS     no  80.666667

In [32]:
df['Status'] = df['Average'].between(71, 100).map({True: 'pass', False: 'fail'})

df

,Name,Python,Maths,Chemistry,Physics,Department,Sports,Average,Status
0,Alice,85,99,90,85,SCMS,yes,89.666667,pass
1,Bob,92,85,65,65,SCMS,no,80.666667,pass
2,Charlie,78,88,75,87,CS,yes,84.333333,pass
3,Diana,90,50,80,33,Physics,yes,57.666667,fail

In [33]:
df[df['Status'] == 'pass']

,Name,Python,Maths,Chemistry,Physics,Department,Sports,Average,Status
0,Alice,85,99,90,85,SCMS,yes,89.666667,pass
1,Bob,92,85,65,65,SCMS,no,80.666667,pass
2,Charlie,78,88,75,87,CS,yes,84.333333,pass

###############################################################################

>We've been creating DataFrames ourselves.\
>But real data usually doesn't arrive as a Python dictionary.
It may come from:

experiments\
databases\
surveys\
instruments\
public datasets\
spreadsheets exported as CSV

### So lets load data using *CSV (Comma Seperated Values)*

```python

import pandas as pd

df = pd.read_csv("bmw_with_missing_data.csv")

df

In [34]:
#code here
import pandas as pd

df = pd.read_csv("bmw_with_missing_data.csv")

df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,NaN,57.6,2.0
1,6 Series,NaN,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,NaN,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,NaN,72.4,1.5
4,7 Series,2014,NaN,Automatic,39554,Diesel,160,50.4,3.0
...,...,...,...,...,...,...,...,...,...
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
103,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
104,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999

### Try this with the loaded df and try to understand the data?

df.head()

df.tail()

df.shape

df.columns

df.index

df.dtypes

df.info()

df.describe()

In [35]:
#code here
df.head()

       model  year  price transmission mileage fuelType  tax   mpg engineSize
0   5 Series  2014  11200    Automatic   67068   Diesel  NaN  57.6        2.0
1   6 Series   NaN  27000    Automatic   14827   Petrol  145  42.8        2.0
2   5 Series  2016  16000          NaN   62794   Diesel  160  51.4        3.0
3   1 Series  2017  12750    Automatic   26676   Diesel  NaN  72.4        1.5
4   7 Series  2014    NaN    Automatic   39554   Diesel  160  50.4        3.0

In [36]:

df.tail()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
103,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
104,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999

In [37]:
df.shape

(107, 9)

In [38]:

df.columns

Index(['model', 'year', 'price', 'transmission', 'mileage', 'fuelType', 'tax',
       'mpg', 'engineSize'],
      dtype='object')

In [39]:

df.index

RangeIndex(start=0, stop=107, step=1)

In [40]:

df.dtypes

model           object
year            object
price           object
transmission    object
mileage         object
fuelType        object
tax             object
mpg             object
engineSize      object
dtype: object

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         98 non-null     object
 1   year          87 non-null     object
 2   price         90 non-null     object
 3   transmission  93 non-null     object
 4   mileage       91 non-null     object
 5   fuelType      93 non-null     object
 6   tax           100 non-null    object
 7   mpg           93 non-null     object
 8   engineSize    106 non-null    object
dtypes: object(9)
memory usage: 7.7+ KB

In [42]:

df.describe()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
count,98,87,90,93,91,93,100,93,106
unique,21,10,63,3,90,6,14,32,7
top,1 Series,2017,14000,Automatic,50000,Diesel,145,62.8,2.0
freq,26,29,7,52,2,66,21,8,67

### <span style="color: green">To Do</span>

1. Find BMWs costing more than £20,000.
2. Cars manufactured after 2017.
3. What types of fuel exist in this dataset?
4. Find transmission using either Automatic.
5. Find cars with mileage between 20,000 and 50,000.
6. How many different fuel types are present?
7. Which transmission type occurs most frequently?

In [43]:
#code here
#q1
df.columns
bmw = df['model'].str.contains('BMW')

In [44]:
price = pd.to_numeric(df['price'], errors='coerce')

In [45]:
expensive = price > 20000

In [46]:
df[bmw & expensive]

     model  year  price transmission mileage fuelType  tax   mpg engineSize
99  BMW Z4  2019  35000    Automatic   15000   Petrol  165  45.2        2.0

In [47]:
#q2
year = pd.to_numeric(df['year'], errors='coerce')
new_cars = year > 2017

df[new_cars]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
7,2 Series,2018,16250,Manual,10401,Petrol,145,52.3,2.0
26,3 Series,2019,17800,Automatic,22310,Diesel,NaN,64.2,2.0
39,1 Series,2018,14600,NaN,6522,Petrol,145,37.2,1.5
43,1 Series,2018,17500,Automatic,14037,NaN,145,54.3,1.5
58,X1,2018,18000,Manual,NaN,Petrol,150,51.4,1.5
71,1 Series,2018,11700,Manual,NaN,Diesel,145,53.3,1.5
88,3 Series,2018,19490,NaN,30703,Diesel,145,57.6,2.0
99,BMW Z4,2019,35000,Automatic,15000,Petrol,165,45.2,2.0
100,BMW i8,2018,NaN,Automatic,12500,Hybrid,0,NaN,1.5
101,UNKNOWN,2020,25000,NaN,8000,Electric,0,200.0,2.0
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999

In [48]:
fuel = df['fuelType']

fuel.unique()

array(['Diesel', 'Petrol', nan, 'Other', 'Hybrid', 'Electric', 'Unknown'],
      dtype=object)

In [49]:
transmission = df['transmission']
automatic = transmission.isin(['Automatic'])

df[automatic]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,NaN,57.6,2.0
1,6 Series,NaN,27000,Automatic,14827,Petrol,145,42.8,2.0
3,1 Series,2017,12750,Automatic,26676,Diesel,NaN,72.4,1.5
4,7 Series,2014,NaN,Automatic,39554,Diesel,160,50.4,3.0
5,NaN,2016,14900,Automatic,35309,Diesel,125,60.1,2.0
6,5 Series,2017,16000,Automatic,NaN,Diesel,125,NaN,2.0
9,5 Series,2016,14250,Automatic,36099,Diesel,20,68.9,2.0
12,X3,2016,15500,Automatic,77823,Diesel,125,54.3,NaN
14,X3,2017,NaN,Automatic,19057,Diesel,145,54.3,2.0
16,NaN,2017,14250,Automatic,55594,Other,135,148.7,2.0
17,3 Series,NaN,16000,Automatic,45456,Diesel,30,64.2,2.0
18,1 Series,2017,15500,Automatic,22812,Diesel,NaN,68.9,1.5
19,4 Series,2014,14000,Automatic,47348,Diesel,125,NaN,2.0
20,1 Series,2015,NaN,Automatic,75124,Diesel,20,70.6,2.0
22,3 Series,2016,15100,Automatic,NaN,Diesel,30,64.2,2.0
24,NaN,2016,14300,Automatic,22461,Diesel,20,67.3,2.0
26,3 Series,2019,17800,Automatic,22310,Diesel,NaN,64.2,2.0
27,3 Series,2016,NaN,Automatic,51994,Diesel,30,62.8,2.0
28,X5,2016,19750,Automatic,NaN,Diesel,165,52.3,2.0
29,X3,2015,17400,Automatic,50316,NaN,200,47.9,3.0
30,4 Series,2017,16800,Automatic,44011,Diesel,150,NaN,2.0
31,X4,NaN,23000,Automatic,34960,Diesel,150,54.3,2.0
33,1 Series,2017,20500,Automatic,NaN,Petrol,145,39.8,3.0
35,2 Series,2017,13000,Automatic,61818,NaN,0,141.2,1.5
38,X1,2017,18900,Automatic,33514,Diesel,145,NaN,2.0
42,X3,2013,NaN,Automatic,79972,Diesel,200,47.1,3.0
43,1 Series,2018,17500,Automatic,14037,NaN,145,54.3,1.5
44,5 Series,NaN,23500,Automatic,25034,Diesel,200,47.9,2.0
45,X1,2016,16700,Automatic,NaN,Diesel,125,60.1,2.0
47,4 Series,2016,15500,Automatic,45856,NaN,30,65.7,2.0
51,5 Series,2014,11000,Automatic,NaN,Diesel,30,62.8,2.0
52,3 Series,2017,18500,Automatic,27139,NaN,160,51.4,3.0
53,1 Series,NaN,12750,Automatic,91563,Diesel,125,60.1,2.0
55,X1,2017,NaN,Automatic,54120,Diesel,30,65.7,2.0
61,1 Series,NaN,14500,Automatic,27245,Diesel,145,NaN,2.0
62,3 Series,2013,12750,Automatic,35736,Diesel,NaN,58.9,2.0
63,X1,2017,NaN,Automatic,55782,Diesel,145,65.7,2.0
69,5 Series,2016,NaN,Automatic,35474,Diesel,125,60.1,2.0
73,5 Series,2016,14400,Automatic,51552,NaN,30,62.8,2.0
78,NaN,2014,15000,Automatic,13858,Diesel,125,57.6,2.0
80,X3,2016,21750,Automatic,NaN,Diesel,150,54.3,2.0
81,2 Series,NaN,13900,Automatic,46281,Petrol,125,NaN,1.5
82,X1,2017,14000,Automatic,54183,NaN,150,65.7,2.0
83,X1,2017,NaN,Automatic,36701,Diesel,30,65.7,2.0
86,2 Series,2017,16000,Automatic,NaN,Other,0,141.2,1.5
87,5 Series,NaN,14000,Automatic,39235,Diesel,30,NaN,2.0
96,X1,2017,17800,Automatic,31238,NaN,145,55.4,2.0
99,BMW Z4,2019,35000,Automatic,15000,Petrol,165,45.2,2.0
100,BMW i8,2018,NaN,Automatic,12500,Hybrid,0,NaN,1.5
103,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
104,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0

In [50]:
mileage = pd.to_numeric(df['mileage'], errors='coerce')
mileage_range = mileage.between(20000, 50000)

df[mileage_range]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
3,1 Series,2017,12750,Automatic,26676,Diesel,NaN,72.4,1.5
4,7 Series,2014,NaN,Automatic,39554,Diesel,160,50.4,3.0
5,NaN,2016,14900,Automatic,35309,Diesel,125,60.1,2.0
8,4 Series,2017,14250,Manual,42668,NaN,30,62.8,2.0
9,5 Series,2016,14250,Automatic,36099,Diesel,20,68.9,2.0
11,1 Series,NaN,11800,Manual,29840,Diesel,20,NaN,2.0
17,3 Series,NaN,16000,Automatic,45456,Diesel,30,64.2,2.0
18,1 Series,2017,15500,Automatic,22812,Diesel,NaN,68.9,1.5
19,4 Series,2014,14000,Automatic,47348,Diesel,125,NaN,2.0
23,1 Series,NaN,9400,Manual,44498,Diesel,0,83.1,1.5
24,NaN,2016,14300,Automatic,22461,Diesel,20,67.3,2.0
25,1 Series,2016,11200,Manual,23005,NaN,125,53.3,1.5
26,3 Series,2019,17800,Automatic,22310,Diesel,NaN,64.2,2.0
30,4 Series,2017,16800,Automatic,44011,Diesel,150,NaN,2.0
31,X4,NaN,23000,Automatic,34960,Diesel,150,54.3,2.0
32,i3,2016,17100,NaN,25269,Other,0,470.8,0.6
34,1 Series,NaN,11900,Manual,22920,Petrol,145,53.3,1.5
37,1 Series,2016,13500,Manual,29226,Diesel,NaN,62.8,2.0
38,X1,2017,18900,Automatic,33514,Diesel,145,NaN,2.0
41,NaN,2016,11400,Manual,21591,Petrol,125,53.3,1.5
44,5 Series,NaN,23500,Automatic,25034,Diesel,200,47.9,2.0
47,4 Series,2016,15500,Automatic,45856,NaN,30,65.7,2.0
48,1 Series,NaN,9400,Manual,48858,Diesel,0,83.1,1.5
49,1 Series,2017,NaN,Manual,40399,Diesel,145,68.9,2.0
52,3 Series,2017,18500,Automatic,27139,NaN,160,51.4,3.0
54,3 Series,2014,14000,Manual,32139,Petrol,205,NaN,2.0
56,X1,NaN,14000,Manual,20925,Diesel,150,68.9,2.0
57,3 Series,2016,12750,NaN,30521,Diesel,20,68.9,2.0
60,NaN,2017,12700,Manual,21809,Petrol,145,53.3,1.5
61,1 Series,NaN,14500,Automatic,27245,Diesel,145,NaN,2.0
62,3 Series,2013,12750,Automatic,35736,Diesel,NaN,58.9,2.0
64,1 Series,2016,10800,NaN,26404,Petrol,125,53.3,1.5
66,NaN,2016,12500,Manual,24111,Petrol,145,47.1,1.6
67,3 Series,2017,13600,Manual,22763,NaN,145,48.7,2.0
69,5 Series,2016,NaN,Automatic,35474,Diesel,125,60.1,2.0
74,1 Series,NaN,11100,Manual,29508,Petrol,125,53.3,1.5
75,1 Series,2017,NaN,Manual,30865,Diesel,145,72.4,1.5
76,5 Series,2014,12400,NaN,46356,Diesel,30,62.8,2.0
79,2 Series,2017,NaN,Manual,33752,Petrol,125,52.3,1.5
81,2 Series,NaN,13900,Automatic,46281,Petrol,125,NaN,1.5
83,X1,2017,NaN,Automatic,36701,Diesel,30,65.7,2.0
84,3 Series,2017,13500,NaN,48082,Petrol,150,51.4,2.0
87,5 Series,NaN,14000,Automatic,39235,Diesel,30,NaN,2.0
88,3 Series,2018,19490,NaN,30703,Diesel,145,57.6,2.0
89,1 Series,2015,15499,Semi-Auto,20000,NaN,125,60.1,2.0
90,2 Series,NaN,13000,Semi-Auto,34971,Diesel,150,72.4,1.5
91,1 Series,2014,NaN,Semi-Auto,44900,Diesel,30,64.2,2.0
93,M4,NaN,29998,Semi-Auto,34209,Petrol,300,34.0,3.0
96,X1,2017,17800,Automatic,31238,NaN,145,55.4,2.0
97,3 Series,NaN,13100,Manual,37204,Diesel,30,64.2,2.0
98,1 Series,2017,NaN,Manual,26265,Diesel,0,83.1,1.5
103,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0
104,DUPLICATE,2016,14000,Automatic,50000,Diesel,125,60.1,2.0

In [51]:
fuel = df['fuelType']
number_of_fuels = fuel.nunique()

number_of_fuels

6

In [52]:
transmission = df['transmission']
counts = transmission.value_counts()

counts.idxmax()

'Automatic'

### Why do we need sorting?

Imagine our dataset contains thousands of cars.

If we want to answer questions such as:

Which cars are the most expensive?\
Which cars are the cheapest?\
Which cars have the highest mileage?\
Which cars are the newest?

Looking at the DataFrame row by row isn't very useful.

We need a way to rearrange the rows according to a particular column.

Pandas provides:

```python 
sort_values()

df.sort_values("column_name")

lets try sorting based on the price

```python 
df.sort_values("price")

if you want to sort in decending order

df.sort_values("price", ascending=False)

In [53]:
#code here
df.sort_values("price")

        model  year  price transmission mileage fuelType  tax   mpg engineSize
13   2 Series  2015  10500       Manual     NaN   Diesel   20  68.9        2.0
64   1 Series  2016  10800          NaN   26404   Petrol  125  53.3        1.5
72   2 Series   NaN  10900       Manual   62021   Diesel  145   NaN        2.0
51   5 Series  2014  11000    Automatic     NaN   Diesel   30  62.8        2.0
74   1 Series   NaN  11100       Manual   29508   Petrol  125  53.3        1.5
..        ...   ...    ...          ...     ...      ...  ...   ...        ...
83         X1  2017    NaN    Automatic   36701   Diesel   30  65.7        2.0
91   1 Series  2014    NaN    Semi-Auto   44900   Diesel   30  64.2        2.0
98   1 Series  2017    NaN       Manual   26265   Diesel    0  83.1        1.5
100    BMW i8  2018    NaN    Automatic   12500   Hybrid    0   NaN        1.5
106  Test Car  2025    NaN       Manual     NaN  Unknown  999   NaN        999

[107 rows x 9 columns]

In [54]:
df.sort_values("price", ascending=False)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
23,1 Series,NaN,9400,Manual,44498,Diesel,0,83.1,1.5
48,1 Series,NaN,9400,Manual,48858,Diesel,0,83.1,1.5
95,NaN,2015,7948,Manual,74375,Diesel,30,NaN,2.0
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0
...,...,...,...,...,...,...,...,...,...
83,X1,2017,NaN,Automatic,36701,Diesel,30,65.7,2.0
91,1 Series,2014,NaN,Semi-Auto,44900,Diesel,30,64.2,2.0
98,1 Series,2017,NaN,Manual,26265,Diesel,0,83.1,1.5
100,BMW i8,2018,NaN,Automatic,12500,Hybrid,0,NaN,1.5
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999

In [57]:
df.sort_values("engineSize")

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
32,i3,2016,17100,NaN,25269,Other,0,470.8,0.6
79,2 Series,2017,NaN,Manual,33752,Petrol,125,52.3,1.5
81,2 Series,NaN,13900,Automatic,46281,Petrol,125,NaN,1.5
59,1 Series,2015,11100,Manual,11524,NaN,0,83.1,1.5
77,1 Series,2016,12800,Manual,NaN,Diesel,20,70.6,1.5
...,...,...,...,...,...,...,...,...,...
33,1 Series,2017,20500,Automatic,NaN,Petrol,145,39.8,3.0
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
12,X3,2016,15500,Automatic,77823,Diesel,125,54.3,NaN

In [58]:
df.sort_values("mpg")

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
86,2 Series,2017,16000,Automatic,NaN,Other,0,141.2,1.5
35,2 Series,2017,13000,Automatic,61818,NaN,0,141.2,1.5
16,NaN,2017,14250,Automatic,55594,Other,135,148.7,2.0
101,UNKNOWN,2020,25000,NaN,8000,Electric,0,200.0,2.0
93,M4,NaN,29998,Semi-Auto,34209,Petrol,300,34.0,3.0
...,...,...,...,...,...,...,...,...,...
81,2 Series,NaN,13900,Automatic,46281,Petrol,125,NaN,1.5
87,5 Series,NaN,14000,Automatic,39235,Diesel,30,NaN,2.0
95,NaN,2015,7948,Manual,74375,Diesel,30,NaN,2.0
100,BMW i8,2018,NaN,Automatic,12500,Hybrid,0,NaN,1.5
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999

### <span style="color: green"> To Do</span>
1. Which cars have the highest mileage?
2. Which cars have the newest model year?
3. Which cars have the largest engine?

In [59]:
#code here
df.sort_values('mileage', ascending=False)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
53,1 Series,NaN,12750,Automatic,91563,Diesel,125,60.1,2.0
101,UNKNOWN,2020,25000,NaN,8000,Electric,0,200.0,2.0
42,X3,2013,NaN,Automatic,79972,Diesel,200,47.1,3.0
21,3 Series,2015,12600,NaN,78957,Diesel,30,62.8,2.0
...,...,...,...,...,...,...,...,...,...
77,1 Series,2016,12800,Manual,NaN,Diesel,20,70.6,1.5
80,X3,2016,21750,Automatic,NaN,Diesel,150,54.3,2.0
86,2 Series,2017,16000,Automatic,NaN,Other,0,141.2,1.5
92,X3,2017,23000,Semi-Auto,NaN,Diesel,150,54.3,2.0
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999

In [60]:
df.sort_values('mileage', ascending=False).head(1)

          model year price transmission mileage fuelType  tax  mpg engineSize
102  ERROR_DATA  abc   xyz       Manual     def   Petrol  ghi  jkl        mno

In [61]:
df.sort_values('year', ascending=False)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0
101,UNKNOWN,2020,25000,NaN,8000,Electric,0,200.0,2.0
99,BMW Z4,2019,35000,Automatic,15000,Petrol,165,45.2,2.0
...,...,...,...,...,...,...,...,...,...
85,X1,NaN,12150,Manual,77482,Diesel,20,68.9,2.0
87,5 Series,NaN,14000,Automatic,39235,Diesel,30,NaN,2.0
90,2 Series,NaN,13000,Semi-Auto,34971,Diesel,150,72.4,1.5
93,M4,NaN,29998,Semi-Auto,34209,Petrol,300,34.0,3.0
97,3 Series,NaN,13100,Manual,37204,Diesel,30,64.2,2.0

In [62]:
df.sort_values('engineSize', ascending=False)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999
29,X3,2015,17400,Automatic,50316,NaN,200,47.9,3.0
33,1 Series,2017,20500,Automatic,NaN,Petrol,145,39.8,3.0
42,X3,2013,NaN,Automatic,79972,Diesel,200,47.1,3.0
...,...,...,...,...,...,...,...,...,...
79,2 Series,2017,NaN,Manual,33752,Petrol,125,52.3,1.5
81,2 Series,NaN,13900,Automatic,46281,Petrol,125,NaN,1.5
25,1 Series,2016,11200,Manual,23005,NaN,125,53.3,1.5
32,i3,2016,17100,NaN,25269,Other,0,470.8,0.6
12,X3,2016,15500,Automatic,77823,Diesel,125,54.3,NaN

In [64]:
df.sort_values('engineSize', ascending=False)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999
29,X3,2015,17400,Automatic,50316,NaN,200,47.9,3.0
33,1 Series,2017,20500,Automatic,NaN,Petrol,145,39.8,3.0
42,X3,2013,NaN,Automatic,79972,Diesel,200,47.1,3.0
...,...,...,...,...,...,...,...,...,...
79,2 Series,2017,NaN,Manual,33752,Petrol,125,52.3,1.5
81,2 Series,NaN,13900,Automatic,46281,Petrol,125,NaN,1.5
25,1 Series,2016,11200,Manual,23005,NaN,125,53.3,1.5
32,i3,2016,17100,NaN,25269,Other,0,470.8,0.6
12,X3,2016,15500,Automatic,77823,Diesel,125,54.3,NaN

### <span style="color:cyan">Think</span>

Did the original df change?

### Sorting by Multiple Columns
Sometimes one column isn't enough.

Suppose two cars have the same price.

We may want to sort those cars further by their mileage.

Pandas allows us to provide a list of columns.

```python
df.sort_values(
    ["price", "mileage"],
    ascending=[False, True]
)

This means:

Sort by price from highest to lowest.
If two cars have the same price, sort those cars by mileage from lowest to highest.

In [65]:
#code here
df.sort_values(
    ["price", "mileage"],
    ascending=[False, True]
)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
102,ERROR_DATA,abc,xyz,Manual,def,Petrol,ghi,jkl,mno
23,1 Series,NaN,9400,Manual,44498,Diesel,0,83.1,1.5
48,1 Series,NaN,9400,Manual,48858,Diesel,0,83.1,1.5
95,NaN,2015,7948,Manual,74375,Diesel,30,NaN,2.0
105,X7,2020,45000,Automatic,5000,Petrol,NaN,42.5,3.0
...,...,...,...,...,...,...,...,...,...
63,X1,2017,NaN,Automatic,55782,Diesel,145,65.7,2.0
36,3 Series,2015,NaN,Manual,59634,Diesel,125,61.4,2.0
20,1 Series,2015,NaN,Automatic,75124,Diesel,20,70.6,2.0
42,X3,2013,NaN,Automatic,79972,Diesel,200,47.1,3.0
106,Test Car,2025,NaN,Manual,NaN,Unknown,999,NaN,999

### <span style="color:cyan">Think</span>

What do you expect this to do?
```python
df.sort_values(
    ["fuelType", "price"]
)

In [66]:
#code here
df.sort_values(
    ["fuelType", "price"]
)

        model  year  price transmission mileage fuelType  tax   mpg engineSize
13   2 Series  2015  10500       Manual     NaN   Diesel   20  68.9        2.0
72   2 Series   NaN  10900       Manual   62021   Diesel  145   NaN        2.0
51   5 Series  2014  11000    Automatic     NaN   Diesel   30  62.8        2.0
0    5 Series  2014  11200    Automatic   67068   Diesel  NaN  57.6        2.0
71   1 Series  2018  11700       Manual     NaN   Diesel  145  53.3        1.5
..        ...   ...    ...          ...     ...      ...  ...   ...        ...
15   3 Series  2017  16500       Manual   16570      NaN  125  58.9        2.0
29         X3  2015  17400    Automatic   50316      NaN  200  47.9        3.0
43   1 Series  2018  17500    Automatic   14037      NaN  145  54.3        1.5
96         X1  2017  17800    Automatic   31238      NaN  145  55.4        2.0
52   3 Series  2017  18500    Automatic   27139      NaN  160  51.4        3.0

[107 rows x 9 columns]

### Basic Statistics

We've sorted the data.

Now let's start asking numerical questions.

For example:

What is the average price of the cars in our dataset?

We could manually add all the prices and divide by the number of cars.

But that's exactly the kind of repetitive calculation that Pandas should handle for us.

Pandas provides common statistical operations directly on Series.

```python 
df["price"].min()
df["price"].max()
df["price"].median()
df["price"].std()

In [67]:
#code here

In [71]:
df["price"].min()
df["price"].max()
df["price"].median()
df["price"].std()

TypeError: '<=' not supported between instances of 'str' and 'float'

### Combining Statistics
Sometimes we don't want to run five separate commands:
>mean()\
>min()\
>max()\
>median()\
>std()

Pandas provides:
>agg()

```python
df["engineSize"].agg(["count", "mean", "min", "max", "median", "std"])

In [73]:
#code here
engine = pd.to_numeric(df["engineSize"], errors="coerce")

In [74]:
engine.agg(["count", "mean", "min", "max", "median", "std"])

count     105.000000
mean       11.440000
min         0.600000
max       999.000000
median      2.000000
std        97.303534
Name: engineSize, dtype: float64

```python
df["engineSize"].agg(["count", "mean", "min", "max", "median", "std"])

We have actually encountered describe() earlier.

Now we can understand what it is doing at a conceptual level:

describe() provides a statistical summary of numerical data.

In [76]:
#code here
engine.count()

np.int64(105)

In [77]:
engine.mean()

np.float64(11.440000000000001)

In [78]:
engine.min()

np.float64(0.6)

In [79]:
engine.max()

np.float64(999.0)

In [80]:
engine.median()

np.float64(2.0)

In [81]:
engine.std()

np.float64(97.30353440493468)

### Missing Data in Real Datasets

In real-world data, it's common to encounter missing or incomplete values.

Missing data can occur due to:
- Data collection errors
- Incomplete surveys
- Equipment failures
- Data entry mistakes
- Intentional omissions

Pandas represents missing data as:
- `NaN` (Not a Number) for numerical data
- `None` for object/string data

Missing data can cause problems in analysis and calculations, so we need to handle it properly.

In [82]:
# Let's create a DataFrame with missing data to explore
import pandas as pd
import numpy as np

# Create sample data with missing values
students_with_missing = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Python': [85, np.nan, 78, 90, np.nan],
    'Maths': [99, 85, np.nan, 50, 88],
    'Chemistry': [90, np.nan, 75, np.nan, 92],
    'Physics': [85, 65, 87, 33, np.nan]
})

print("DataFrame with Missing Values:")
print(students_with_missing)
print("\nData types:")
print(students_with_missing.dtypes)

DataFrame with Missing Values:
      Name  Python  Maths  Chemistry  Physics
0    Alice    85.0   99.0       90.0     85.0
1      Bob     NaN   85.0        NaN     65.0
2  Charlie    78.0    NaN       75.0     87.0
3    Diana    90.0   50.0        NaN     33.0
4      Eve     NaN   88.0       92.0      NaN

Data types:
Name          object
Python       float64
Maths        float64
Chemistry    float64
Physics      float64
dtype: object

### Detecting Missing Data

Pandas provides methods to identify where missing values are:

- `isnull()` or `isna()` - Returns True where values are missing
- `notnull()` or `notna()` - Returns True where values are NOT missing
- `info()` - Shows count of non-null values for each column

Try these commands:
```python
students_with_missing.isnull()
students_with_missing.isna()
students_with_missing.isnull().sum()  # Count missing values per column
students_with_missing.info()
```

In [88]:
# code here
# Test isnull(), isna(), and info() methods to identify missing data
students_with_missing.isnull()

    Name  Python  Maths  Chemistry  Physics
0  False   False  False      False    False
1  False    True  False       True    False
2  False   False   True      False    False
3  False   False  False       True    False
4  False    True  False      False     True

In [89]:
students_with_missing.isna()

    Name  Python  Maths  Chemistry  Physics
0  False   False  False      False    False
1  False    True  False       True    False
2  False   False   True      False    False
3  False   False  False       True    False
4  False    True  False      False     True

In [90]:
students_with_missing.isnull().sum()  # Count missing values per column

Name         0
Python       2
Maths        1
Chemistry    2
Physics      1
dtype: int64

In [91]:
students_with_missing.isnull()

    Name  Python  Maths  Chemistry  Physics
0  False   False  False      False    False
1  False    True  False       True    False
2  False   False   True      False    False
3  False   False  False       True    False
4  False    True  False      False     True

In [92]:
students_with_missing.isna()

    Name  Python  Maths  Chemistry  Physics
0  False   False  False      False    False
1  False    True  False       True    False
2  False   False   True      False    False
3  False   False  False       True    False
4  False    True  False      False     True

In [93]:
students_with_missing.isnull().sum()  # Count missing values per column

Name         0
Python       2
Maths        1
Chemistry    2
Physics      1
dtype: int64

In [94]:
students_with_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Python     3 non-null      float64
 2   Maths      4 non-null      float64
 3   Chemistry  3 non-null      float64
 4   Physics    4 non-null      float64
dtypes: float64(4), object(1)
memory usage: 332.0+ bytes

In [95]:
students_with_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Python     3 non-null      float64
 2   Maths      4 non-null      float64
 3   Chemistry  3 non-null      float64
 4   Physics    4 non-null      float64
dtypes: float64(4), object(1)
memory usage: 332.0+ bytes

### Handling Missing Data: dropna()

`dropna()` removes rows or columns containing missing values.

**Strategies:**
- Drop entire rows with ANY missing value
- Drop entire columns with ANY missing value
- Drop rows where ALL values are missing
- Drop columns where ALL values are missing

**Syntax:**
```python
df.dropna()                           # Remove rows with any NaN
df.dropna(axis=1)                     # Remove columns with any NaN
df.dropna(how='all')                  # Remove rows where ALL values are NaN
df.dropna(subset=['column_name'])     # Remove rows where specific column has NaN
df.dropna(thresh=3)                   # Keep rows with at least 3 non-null values
```

**Warning:** Dropping rows/columns removes data! Use with caution.

In [25]:
# code here
# Try different dropna() strategies:
# 1. Remove rows with any NaN
# 2. Remove columns with any NaN
# 3. Remove rows where all values are NaN
# 4. Remove rows where specific columns have NaN

In [96]:
students_with_missing = df.copy()

In [ ]:
students_with_missing.loc[1, "Maths"] = None
students_with_missing.loc[2, "Chemistry"] = None
students_with_missing.loc[3, "Python"] = None

students_with_missing

### Handling Missing Data: fillna()

`fillna()` replaces missing values with specified values instead of removing data.

This is often better than dropping data because it preserves row/column count.

**Methods:**
```python
df.fillna(0)                          # Replace all NaN with 0
df.fillna('Unknown')                  # Replace with a specific value
df.fillna(method='ffill')             # Forward fill: use previous value
df.fillna(method='bfill')             # Backward fill: use next value
df['column'].fillna(df['column'].mean())  # Fill with mean/median/mode
df.fillna({'col1': 0, 'col2': 'N/A'}) # Fill different columns differently
```

**Forward Fill (ffill):** Propagates the last known value forward
**Backward Fill (bfill):** Propagates the next known value backward

In [26]:
# code here
# Try different fillna() strategies:
# 1. Fill with a constant value (0 or 'Unknown')
# 2. Fill with mean of the column
# 3. Use forward fill (ffill)
# 4. Fill different columns with different values
# 5. Compare: Which approach preserves the most data?

### Grouping Data with groupby()

`groupby()` splits data into groups based on one or more columns, then applies operations to each group.

This is powerful for answering questions like:
- "What is the average score per department?"
- "How many students are in each department?"
- "What is the total sales per region?"

**Basic Syntax:**
```python
df.groupby('column').operation()
```

**Common Operations:**
```python
df.groupby('Department').mean()       # Average for each group
df.groupby('Department').sum()        # Sum for each group
df.groupby('Department').count()      # Count of rows in each group
df.groupby('Department').min()        # Minimum value in each group
df.groupby('Department').max()        # Maximum value in each group
df.groupby('Department').agg(['mean', 'sum', 'count'])  # Multiple operations
```

**Grouping by Multiple Columns:**
```python
df.groupby(['Department', 'Gender']).mean()  # Nested grouping
```

In [27]:
# Let's create a fresh DataFrame to practice groupby()
# First, let's use our original students DataFrame with the Department column

# Quick refresh - create the students DataFrame
df_students = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Python': [85, 92, 78, 90],
    'Maths': [99, 85, 88, 50],
    'Chemistry': [90, 65, 75, 80],
    'Physics': [85, 65, 87, 33],
    'Department': ['SCMS', 'SCMS', 'CS', 'Physics']
})

print(df_students)

      Name  Python  Maths  Chemistry  Physics Department
0    Alice      85     99         90       85       SCMS
1      Bob      92     85         65       65       SCMS
2  Charlie      78     88         75       87         CS
3    Diana      90     50         80       33    Physics

In [28]:
# code here
# Try these groupby() operations:
# 1. Group by Department and calculate mean marks
# 2. Group by Department and calculate sum of marks
# 3. Group by Department and count students
# 4. Find the department with the highest average Python score
# 5. Use agg() to get multiple statistics at once

### <span style="color: green">To Do - Practical Exercises</span>

**Using the BMW dataset (bmw_with_missing_data.csv):**

1. **Missing Data Exploration:**
   - Load the BMW dataset
   - Identify which columns have missing values using `isnull()` and `sum()`
   - Count total missing values in the dataset

2. **Using dropna():**
   - Remove all rows with any missing values
   - Remove only rows where the 'price' column is missing
   - Compare the original dataset size with the cleaned dataset

3. **Using fillna():**
   - Fill missing values in 'mileage' with the median
   - Fill missing values in 'fuelType' with 'Unknown'
   - Fill missing values in 'engineSize' with the mean
   - Display the resulting DataFrame

4. **Using groupby():**
   - Group by 'fuelType' and calculate average price
   - Group by 'transmission' and calculate average mileage
   - Group by 'fuelType' and find the count of cars
   - Use agg() to get mean, min, and max price by fuel type

In [29]:
# code here
# Solve all the practical exercises above
# Work through each task step by step